config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  resources :checkins

  resources :eventos

  get 'home/index'

  devise_for :users
  post '/generate' => 'verifications#generate_code'
  post '/verify' => 'verifications#verify_code'
  post '/checkins', :to =>  'checkins#check'
  get '/validacion', :to =>  'checkins#error'
  get '/generate' => 'verifications#generate_code'
  post '/verificar' => 'checkins#validacion'
  get '/validando', :to =>  'checkins#compro'
  get '/evento_no_existe', :to =>  'checkins#no_existe'
  get '/thaks', :to =>  'checkins#gracias'
  get '/successful', :to =>  'eventos#exitoso'
  get '/editando', :to =>  'eventos#edit'

   root 'home#index'
    

end

app/models/evento.rb
class Evento < ActiveRecord::Base
	attr_accessible :nombre, :codigo, :user_id
	has_many :checkins
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def exitoso
    @e = params[:code]
    @evento = Evento.where(:codigo => @e).pluck(:nombre).first
    @numero = Evento.where(:codigo => @e).pluck(:codigo).first
    logger.debug "Prueba #{@e}"
  end

  def index
    @name = Profile.where(:user_id.to_s => current_user.id.to_s).count
    if @name != 0 
     @eventos = Evento.all
    else
     redirect_to :controller => 'profiles', :action => 'new'
    end
  end

  def show
    respond_with(@evento)
  end

  def new
    @eventos = Evento.where(:user_id.to_s => current_user.id.to_s).order(:id => :desc)
    @codigo = Random.rand(100000..999999).to_s
    @evento = Evento.new
    respond_with(@evento)
  end

  def edit
  end

  def create
    # @evento = Evento.new(evento_params)
    # @evento.save
    @evento = Evento.create({
    :nombre => params[:name], 
    :codigo => params[:code],
    :user_id => current_user.id
    });
    @evento.save

    redirect_to  :action => 'exitoso', :code => params[:code]
  end

  def update
    @evento.update(evento_params)
    respond_with(@evento)
  end

  def destroy
    @evento.destroy
    respond_with(@evento)
  end

  private
    def set_evento
      @evento = Evento.find(params[:id])
    end

    def evento_params
      params.require(:evento).permit(:nombre, :codigo)
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_evento.html.erb
<style type="text/css">
 .row{
 	margin-top: 150px;
}

.button.button-success.button-cons{
  background-color: #16A085!important;
  border-color: #16A085!important;
  color: white!important;
}
.button.button-success.button-cons:hover{
 background-color: #1ABC9C!important;
  border-color: #1ABC9C!important;
  color: white!important;
}
.panel{
  background-color: hsl(210, 29%, 29%)!important;
  text-align: center!important;

}
h6{
  font-size: 20px!important;
  color: white!important;
}

</style>
<div class="row">
	<div class="panel">
	<h6> El evento "<strong><%= @evento %></strong>" ha sido creado satisfactoriamente, <span>comparte este evento con el siguiente número: <strong><%= @numero %></strong></span></h6>
  <%= link_to 'Aceptar', "/eventos/new", :class => "button button-success button-cons" %>
  </div>
</div>

app/views/eventos/_form.html.erb
<style type="text/css">
li.student-card-list-item{

   margin-left: auto!important;
   margin-right: auto !important;
   width: 100%;
  }
div.twelve.columns{
  margin-bottom: 10px!important;
  margin-top: 0px!important;
}
.student-card{
  margin-bottom: 0px!important;
  margin-top: 0px!important;
}
.student-card-list{
  margin: 0px!important;
}
h6{
  font-size: 20px!important;
  color: white!important;
}
h6.a{
  color:hsl(210, 29%, 29%)!important;
}
.boton{
  background-color: #16A085!important;
  border-color: #16A085!important;
  color: white!important;
}

.boton:hover{
  background-color: #1ABC9C!important;
  border-color: #1ABC9C!important;
  color: white!important;
}
.panel{
  background-color: hsl(210, 29%, 29%)!important;

}


</style>
<link rel="stylesheet" type="text/css" href="/assets/estilo.css">

<br>
<br>
<br>
<br>
<br>
<br>
<div class="row">
  <div class ="panel">
  <%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h6>Nombre del evento</h6>
    <%= f.text_field :nombre, :name => "name",:placeholder=> "ejemplo: Junta de seguimiento", :required => true %>
  </div>
  <div class="field">
    <h6>Código del evento</h6>
    <%= f.text_field :codigo, :name => "code", :value => @codigo, :readonly => "true" %>
  </div>
  <div class="actions">
    <%= f.submit "Crear", :class => "boton" %>
  </div>
<% end %>

</div>
</div>
<div class="row">
<h6 class="a">Mis eventos</h6>
<% if @eventos.nil? %>
<% else %>
<% @eventos.each do |evento| %>
    <div class="twelve columns">
            <ul class="student-card-list initial-list">
                <li class="student-card-list-item">
                  <a class="student-card" href="<%= evento.id %>">
                    <h4 class="student-card-name"><%= evento.nombre %></h4>
                    <span class="student-card-location">Codigo <%= evento.codigo %></span>
                     <span class="student-card-location">Participantes <%= evento.checkins.count %></span>
                     
                  </a>
                </li>
            </ul>
    </div>
<% end %>
<% end %>
</div>

app/views/eventos/edit.html.erb
<h1>Editing evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/exitoso.html.erb
<%= render 'evento' %>

app/views/eventos/index.html.erb
<h1>Listing eventos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.nombre %></td>
        <td><%= evento.codigo %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<%= render 'form' %>

app/views/eventos/show.html.erb
<style type="text/css">
.row{
		margin-top: 90px!important;

	}
li.student-card-list-item{

   margin-left: auto!important;
   margin-right: auto !important;
   width: 100%;
   height: auto!important;
  }
div.twelve.columns{
  margin-bottom: 10px!important;
  margin-top: 0px!important;
}
.student-card{
  margin-bottom: 0px!important;
  margin-top: 0px!important;
  height: 120px!important;
}
.student-card-list{
  margin: 0px!important;
}
.student-card-puesto{
  float: right;
}
.panel{
  background-color: hsl(210, 29%, 29%)!important;


}
.label{
  font-size: 22px!important;
  color: white!important;
  font-weight: 700!important;
  line-height: 

}
 .evento{
 	font-size: 20px!important;
 }

.blanco{
	color: white!important;
	font-size: 20px!important;
}

a{
	color:  hsl(210, 29%, 29%)!important;
}
</style>

<div class="row"> 
	<div class="panel">
  
    <span class="label">Nombre del evento: </span><span class="blanco"><%= @evento.nombre %></span><br><br>
  	<strong class="label">Codigo: </strong><label class="blanco"><%= @evento.codigo %></label>
  	
  
</div>

<div class="panel1">
	<h4>Listado de Participantes</h4>


	 <% @evento.checkins.each do |checkin| %>
			<div class="twelve columns">
			            <ul class="student-card-list initial-list">
			                <li class="student-card-list-item">
			                  <a class="student-card" href="#">
			                    <h4 class="student-card-name"><%= checkin.nombre %>
			                    	 <span class="student-card-puesto">Empresa: <%= checkin.empresa %></span>
			                    </h4>
			                     <span class="student-card-correo">Correo: <%= checkin.correo  %></span><br>
			                     <span class="student-card-empresa">Puesto: <%= checkin.puesto  %></span>
			                   
			                  </a>
			                </li>
			            </ul>
			    </div>
			   
    <% end %>


</div>
</div>