config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  resources :checkins

  resources :eventos

  get 'home/index'

  devise_for :users
  post '/generate' => 'verifications#generate_code'
  post '/verify' => 'verifications#verify_code'
  post '/checkins', :to =>  'checkins#check'
  get '/validacion', :to =>  'checkins#error'
  get '/generate' => 'verifications#generate_code'
  post '/verificar' => 'checkins#validacion'
  get '/validando', :to =>  'checkins#compro'
  get '/evento_no_existe', :to =>  'checkins#no_existe'
  get '/thaks', :to =>  'checkins#gracias'
  get '/successful', :to =>  'eventos#exitoso'
  get '/editando', :to =>  'eventos#edit'

   root 'home#index'
    

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
	attr_accessible :codigo_evento, :nombre, :puesto,:correo,:nombre_evento, :evento_id, :empresa
	belongs_to :evento
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :set_checkin, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def validacion
        phone_number = params["phone_number"]
        code = params["code"] 
        email = Verification.where(phone_number: phone_number, code: code).pluck(:movil).first
        evento = Verification.where(phone_number: phone_number, code: code).pluck(:codigo_evento).first
        verification = Verification.where(phone_number: phone_number, code: code).first
        if verification
           verification.destroy
            check = Checkin.where(:correo => email, :codigo_evento => evento).first
            check.update(:nombre_evento => 1)
            #render status: 200, json: {verified: true}.to_json
            redirect_to :action => 'gracias'
             
        else
            render status: 200, json: {verified: false}.to_json
            #redirect_to :controller => 'home', :action => 'index'
        end
  end

  def error

  end

  def compro

  end

  def gracias

  end


  def index
    @name = Profile.where(:user_id.to_s => current_user.id.to_s).count
    if @name != 0 
     @checkins = Checkin.all
    else
     redirect_to :controller => 'profiles', :action => 'new'
    
    end
  end

  def show
    respond_with(@checkin)
  end

  def new
    @nombre = Profile.where(:user_id.to_s => current_user.id.to_s).pluck(:nombre).first
    @puesto = Profile.where(:user_id.to_s => current_user.id.to_s).pluck(:puesto).first
    @email = User.where(:id => current_user.id).pluck(:email).first

    @checkin = Checkin.new
    respond_with(@checkin)
  end

  def edit
  end

  def create
    @codigo = params[:codigo_evento] 
    @evento_id = Evento.where(:codigo => params[:codigo_evento]).pluck(:id).first
    logger.debug @evento_id
    @empresa = Profile.where(:user_id.to_s => current_user.id.to_s).pluck(:empresa).first

      #@checkin = Checkin.new(checkin_params)
      #@checkin.save
      #respond_with(@checkin)

    #### valida si existe el evento.
    @valida = Evento.where(:codigo => params[:codigo_evento]).count
   if @valida != 0
     #--Primer Condición -- "El valor es igual a 1, entonces valida que exista el checkin, con el parametro 1
     #render status: 200, json: {existe: true}.to_json
     #--Segunda Condición -- Valida que exista un checkin con valor 2
     @verifica = Checkin.where(:codigo_evento => params[:codigo_evento] , :correo => current_user.email, :nombre_evento => "2").count
    if @verifica != 0
     #Si el valor es mayor a 1 
     #render status: 200, json: {existe: true}.to_json
       redirect_to :action => 'error', :event => params[:codigo_evento]
    else @verifica.nil?
     #Si el checkin no existe, se crea
       @verifica1 = Checkin.where(:codigo_evento => params[:codigo_evento] , :correo => current_user.email, :nombre_evento => "1").count
    if @verifica1 == 1
        #verifica si el checkin tiene el valor 1
        redirect_to :action => 'compro'
     else
        #si no tiene el valor 1, crea el checkin
        
        @checkin = Checkin.create({
        :codigo_evento => params[:codigo_evento], 
        :nombre => params[:nombre],
        :puesto => params[:puesto],
        :correo => params[:correo],
        :nombre_evento => params[:nombre_evento],
        :evento_id => @evento_id,
        :empresa => @empresa
        });
        @checkin.save
        #redirect_to :controller => 'verifications', :action => 'generate_code', :phone_number => '+525548225097', :type => 'post'
        @telefono = Profile.where(:user_id.to_s => current_user.id.to_s).pluck(:movil).first
        phone_number = @telefono
        code = Random.rand(10000..99999).to_s
        Verification.create(phone_number: phone_number, code: code, movil: params[:correo], codigo_evento: params[:codigo_evento] )
        SinchSms.send('53c3f2a5-23e6-400c-8b56-442b67e7f442', '4i7JtsBJsEqex9B6W49+YA==', "Access code #{code}", phone_number)
        #render status: 200, nothing: true
        redirect_to :action => 'error'
        #render status: 200, json: {existe: false}.to_json
      end
    end
    else 
    #-- Primera condición -- "El Valor es igual a 0
     redirect_to :action => 'no_existe'
     #render status: 200, json: {existe: false}.to_json
   end  
    
  end

  def no_existe
    
  end

  def update
    @checkin.update(checkin_params)
    respond_with(@checkin)
  end

  def destroy
    @checkin.destroy
    respond_with(@checkin)
  end

  private
    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    def checkin_params
      params.require(:checkin).permit(:codigo_evento, :nombre, :puesto, :correo)
    end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/views/checkins/_comprobar.html.erb
<style type="text/css">
.row{
 	margin-top: 150px;
}

.button.button-success.button-cons{
  background-color: #16A085!important;
  border-color: #16A085!important;
  color: white!important;
}
.button.button-success.button-cons:hover{
 background-color: #1ABC9C!important;
  border-color: #1ABC9C!important;
  color: white!important;
}
.panel{
  background-color: hsl(210, 29%, 29%)!important;
  text-align: center!important;

}
h6{
  font-size: 20px!important;
  color: white!important;
}
</style>
<div class="row">
	<div class="panel">
	  <h6>Ya tienes una participación en este evento, te recomendamos intentar con otro número</h6>
	  <%= link_to 'Aceptar', "/checkins/new", :class => "button button-success button-cons" %>
  </div>
</div>

app/views/checkins/_existe.html.erb
<style type="text/css">
 .row{
 	margin-top: 150px;
}
.boton{
  background-color: #16A085!important;
  border-color: #16A085!important;
  color: white!important;
}

.boton:hover{
  background-color: #1ABC9C!important;
  border-color: #1ABC9C!important;
  color: white!important;
}
.panel{
  background-color: hsl(210, 29%, 29%)!important;
  text-align: center!important;

}
h6{
  font-size: 20px!important;
  color: white!important;
}
input{
  width: 45%!important;
  text-align: center!important;
  font-size: 20px!important;
  color: hsl(210, 29%, 29%)!important;
}
</style>
<div class="row">
  <div class="panel">
    	<h6> Ingresa el codigo de verificación y participa en este evento</h6>
    	<%= form_tag :controller => 'checkins', :action => 'validacion', :method => 'post' do %>
      <div class="field">
        <%= text_field_tag :code, nil, :value => nil ,:class => 'form-control tamano' %>
      </div>
      <div class="field">
      
        <%= hidden_field_tag :phone_number, nil, :value => "+525548225097" ,:class => 'form-control tamano' %>
      </div>
      <%= submit_tag "Verificar", :class => "boton" %>
    <% end %>
  </div>
</div>

app/views/checkins/_form.html.erb
<style type="text/css">
 h6{
  font-size: 20px!important;
  color: white!important;
  text-align: center!important;
}
input{
  width: 45%!important;
  margin-left: 28%!important;
  margin-right: 30%!important;
}
.boton{
  background-color: #16A085!important;
  border-color: #16A085!important;
  color: white!important;
}

.boton:hover{
  background-color: #1ABC9C!important;
  border-color: #1ABC9C!important;
  color: white!important;
}
.panel{
  background-color: hsl(210, 29%, 29%)!important;

}
.font{
  text-align: center!important;
  font-size: 20px!important;
  color: hsl(210, 29%, 29%)!important;
}



</style>
<div class="row">
    <%= form_for(@checkin) do |f| %>
      <% if @checkin.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

          <ul>
          <% @checkin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    <div class="panel">
      <div class="field">
        <h6>Ingresa el número del evento</h6>
        <%= f.text_field :codigo_evento, :name => "codigo_evento", :required => true,:class => "font"  %>
      </div>
      <div class="field">
        <%= f.hidden_field :nombre,:name => "nombre", :value => @nombre %>
      </div>
      <div class="field">
        <%= f.hidden_field :puesto,:name => "puesto", :value => @puesto %>
      </div>
      <div class="field">
        <%= f.hidden_field :correo,:name => "correo", :value => @email %>
      </div>
      <div class="field">
        <%= f.hidden_field :nombre_evento,:name => "nombre_evento", :value => "2" %>
      </div>
      <div class="actions">
        <%= f.submit "Checkin", :class=>"boton" %>
      </div>
      <h6>Le será enviado un SMS con tú código de participación</h6>
    <% end %>
  </div>
</div>

app/views/checkins/_validar.html.erb
<style type="text/css">
 .row{
 	margin-top: 150px;
 	margin-left: 15%;
 	margin-right: 15%;
 }
</style>
<div class="row">
	<h2> Ingresa el codigo de verificación y participa en este evento</h2>
	<%= form_tag :controller => 'checkins', :action => 'validacion', :method => 'post', :event => params[:event] do %>
  <div class="field">
    <%= label_tag "Ingresa el codigo verificación" %><br>
    <%= text_field_tag :code, nil, :value => "nil" ,:class => 'form-control tamano' %>
  </div>
  <div class="field">
  
    <%= text_field_tag :phone_number, nil, :value => "+525548225097" ,:class => 'form-control tamano' %>

  </div>
  <%= submit_tag "Verificar", :class => "btn btn-success btn-cons" %>
<% end %>
</div>

app/views/checkins/compro.html.erb
<%= render 'comprobar' %>

app/views/checkins/edit.html.erb
<h1>Editing checkin</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkin %> |
<%= link_to 'Back', checkins_path %>

app/views/checkins/error.html.erb
<%= render 'existe' %>

app/views/checkins/gracias.html.erb
<style type="text/css">
 .row{
 	margin-top: 150px;
}

.button.button-success.button-cons{
  background-color: #16A085!important;
  border-color: #16A085!important;
  color: white!important;
}
.button.button-success.button-cons:hover{
 background-color: #1ABC9C!important;
  border-color: #1ABC9C!important;
  color: white!important;
}
.panel{
  background-color: hsl(210, 29%, 29%)!important;
  text-align: center!important;

}
h6{
  font-size: 20px!important;
  color: white!important;
}
.i{
    color: hsl(194, 64%, 55%)!important;
  }

.logo{
    height: 53px!important;
    font-size: 30px!important;
    font-weight: 700!important;
    line-height: 1.042!important;
  }

</style>
<div class="row">
  <div class="panel">
  <h6>Gracias por tú participación... <span class="logo">tzir<span class="i">i</span></span></h6>
  <%= link_to 'Aceptar', "/", :class => "button button-success button-cons" %>
  </div>
</div>

app/views/checkins/index.html.erb
<h1>Listing checkins</h1>

<table>
  <thead>
    <tr>
      <th>Codigo evento</th>
      <th>Nombre</th>
      <th>Puesto</th>
      <th>Correo</th>
      <th>Nombre evento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checkins.each do |checkin| %>
      <tr>
        <td><%= checkin.codigo_evento %></td>
        <td><%= checkin.nombre %></td>
        <td><%= checkin.puesto %></td>
        <td><%= checkin.correo %></td>
        <td><%= checkin.nombre_evento %></td>
        <td><%= link_to 'Show', checkin %></td>
        <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
        <td><%= link_to 'Destroy', checkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checkin', new_checkin_path %>

app/views/checkins/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<%= render 'form' %>

app/views/checkins/no_existe.html.erb
<style type="text/css">
.row{
 	margin-top: 150px;
}
.button.button-success.button-cons{
  background-color: #16A085!important;
  border-color: #16A085!important;
  color: white!important;
}
.button.button-success.button-cons:hover{
 background-color: #1ABC9C!important;
  border-color: #1ABC9C!important;
  color: white!important;
}
.panel{
  background-color: hsl(210, 29%, 29%)!important;
  text-align: center!important;

}
h6{
  font-size: 20px!important;
  color: white!important;
}
input{
  width: 45%!important;
  text-align: center!important;
  font-size: 20px!important;
  color: hsl(210, 29%, 29%)!important;
}
</style>
<div class="row">
	<div class="panel">
	  <h6>Error, el evento ingresado no existe, intentalo con otro número</h6>
	  <%= link_to 'Aceptar', "/checkins/new", :class => "button button-success button-cons" %>
  </div>
</div>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo evento:</strong>
  <%= @checkin.codigo_evento %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @checkin.nombre %>
</p>

<p>
  <strong>Puesto:</strong>
  <%= @checkin.puesto %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @checkin.correo %>
</p>

<p>
  <strong>Nombre evento:</strong>
  <%= @checkin.nombre_evento %>
</p>

<%= link_to 'Edit', edit_checkin_path(@checkin) %> |
<%= link_to 'Back', checkins_path %>

app/views/checkins/validacion.html.erb
<%= render 'validar' %>